package olympus.ascension;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.BorderFactory;
import java.io.IOException;
import java.util.StringJoiner;
import java.util.logging.Level;
import java.util.logging.Logger;

public class StartMenu extends javax.swing.JFrame {
    
    private String selected;
    CustomMenu cMenu;
    //ArrayList<String> gameMovements = new ArrayList<>(); for future customization, use ArrayList
    String[] gameMovements = {"Jumping Jacks", "Burpees", "Step Touches", "Marches"};
    private static String gameDifficulty = "";
    private static String string_gameMovements;

    /**
     * Creates new form StartMenu
     */
    public StartMenu() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        getRootPane().setBorder(BorderFactory.createLineBorder(new java.awt.Color(89, 149, 157), 10));
        label_olympusAscension = new javax.swing.JLabel();
        btn_start = new javax.swing.JButton();
        btn_easy = new javax.swing.JToggleButton();
        btn_hard = new javax.swing.JButton();
        label_hermesChallenge = new javax.swing.JLabel();
        btn_medium = new javax.swing.JButton();
        label_difficulty = new javax.swing.JLabel();
        label_error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Olympus Ascension!");
        setBackground(new java.awt.Color(174, 217, 224));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        label_olympusAscension.setFont(new java.awt.Font("Javanese Text", 0, 85)); // NOI18N
        label_olympusAscension.setForeground(new java.awt.Color(89, 149, 157));
        label_olympusAscension.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_olympusAscension.setText("Bunny Bounce");
        label_olympusAscension.setToolTipText("");
        label_olympusAscension.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        label_olympusAscension.setPreferredSize(new java.awt.Dimension(740, 218));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        getContentPane().add(label_olympusAscension, gridBagConstraints);

        btn_start.setBackground(new java.awt.Color(186, 224, 230));
        btn_start.setFont(new java.awt.Font("Gabriola", 0, 36)); // NOI18N
        btn_start.setForeground(new java.awt.Color(89, 149, 157));
        btn_start.setText("<html><u>Start</u></html>");
        btn_start.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(89, 149, 157), 4, true), javax.swing.BorderFactory.createEmptyBorder(1, 1, 30, 1)));
        btn_start.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_start.setPreferredSize(new java.awt.Dimension(91, 71));
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        getContentPane().add(btn_start, gridBagConstraints);
        btn_start.getAccessibleContext().setAccessibleName("Start Game");

        btn_easy.setBackground(new java.awt.Color(186, 224, 230));
        btn_easy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Easy.png"))); // NOI18N
        btn_easy.setToolTipText("");
        btn_easy.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        btn_easy.setContentAreaFilled(false);
        btn_easy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_easy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_easyActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        getContentPane().add(btn_easy, gridBagConstraints);

        btn_hard.setBackground(new java.awt.Color(186, 224, 230));
        btn_hard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hard.jpg"))); // NOI18N
        btn_hard.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        btn_hard.setContentAreaFilled(false);
        btn_hard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_hard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hardActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        getContentPane().add(btn_hard, gridBagConstraints);

        label_hermesChallenge.setFont(new java.awt.Font("Gabriola", 0, 48)); // NOI18N
        label_hermesChallenge.setForeground(new java.awt.Color(89, 149, 157));
        label_hermesChallenge.setText("The Toybox Trials");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(label_hermesChallenge, gridBagConstraints);

        btn_medium.setBackground(new java.awt.Color(186, 224, 230));
        btn_medium.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Medium.png"))); // NOI18N
        btn_medium.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        btn_medium.setContentAreaFilled(false);
        btn_medium.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_medium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mediumActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        getContentPane().add(btn_medium, gridBagConstraints);

        label_difficulty.setFont(new java.awt.Font("Gabriola", 0, 36)); // NOI18N
        label_difficulty.setForeground(new java.awt.Color(89, 149, 157));
        label_difficulty.setText("Difficulty...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(label_difficulty, gridBagConstraints);

        label_error.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        label_error.setForeground(new java.awt.Color(236, 160, 255));
        label_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_error.setText(" ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(label_error, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        switch(selected) { 
            case "Easy":
                gameDifficulty = "Easy";
                break;
            case "Medium":
                gameDifficulty = "Medium";
                break;
            case "Hard":
                gameDifficulty = "Hard";
                break;
            default:
                label_error.setText("Please select a difficulty.");
                return;
        }
        
        StringJoiner joiner = new StringJoiner(",");
        for(String movement : gameMovements) {
            joiner.add(movement);
        }
        
        string_gameMovements = joiner.toString();
        
        dispose();
        DesktopLauncher.startGame();
    }//GEN-LAST:event_btn_startActionPerformed

    public static String getString_GameMovements() {
        return string_gameMovements;
    }
    
    public static String getGameDifficulty() {
        return gameDifficulty;
    }
    
    private void btn_easyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_easyActionPerformed
        selected = "Easy";
        updateSelected();
    }//GEN-LAST:event_btn_easyActionPerformed

    private void btn_mediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mediumActionPerformed
        selected = "Medium";
        updateSelected();
    }//GEN-LAST:event_btn_mediumActionPerformed

    private void btn_hardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hardActionPerformed
        selected = "Hard";
        updateSelected();
    }//GEN-LAST:event_btn_hardActionPerformed

    public void updateSelected() {
        btn_easy.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        btn_medium.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        btn_hard.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        if(!label_error.getText().equals(" ")) label_error.setText(" ");
        
        switch(selected) {
            
            case "Easy":
                btn_easy.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 8, true));
                break;
            case "Medium":
                btn_medium.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 8, true));
                break;
            case "Hard":
                btn_hard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 8, true));
                break;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_easy;
    private javax.swing.JButton btn_hard;
    private javax.swing.JButton btn_medium;
    private javax.swing.JButton btn_start;
    private javax.swing.JLabel label_difficulty;
    private javax.swing.JLabel label_error;
    private javax.swing.JLabel label_hermesChallenge;
    private javax.swing.JLabel label_olympusAscension;
    // End of variables declaration//GEN-END:variables
}
